Improvements to displayed information

diff --git a/docs/scripts/test b/docs/scripts/test
--- a/docs/scripts/test
+++ b/docs/scripts/test
@@ -22,8 +22,8 @@ checkHeaders() {
 
     # Ensure headers exactly match
     if [[ "$headers" != "$desiredHeaders" ]]; then
-        echo "Invalid set of headers: $headers"
-        echo "Expected: $desiredHeaders"
+        error "Invalid set of headers: $headers"
+        error "Expected: $desiredHeaders"
 
         return 1
     fi
@@ -33,22 +33,22 @@ testCategory() {
     local content evalMe
 
     if [[ "${1##*/}" =~ [^-a-z.0-9] ]]; then
-        echo "Invalid filename"
+        error "Invalid filename"
         return 1
     fi
 
     if [[ "$1" != *.md ]]; then
-        echo "Invalid extension"
+        error "Invalid extension"
         return 1
     fi
 
     if ! loadFile evalMe content "$1"; then
-        echo "Unable to load file"
+        error "Unable to load file"
         return 1
     fi
 
     if ! eval "$evalMe"; then
-        echo "Failure to eval the returned file data"
+        error "Failure to eval the returned file data"
         return 1
     fi
 
@@ -63,23 +63,23 @@ testCsi() {
     local content evalMe
 
     if [[ "${1##*/}" =~ [^-a-z.0-9] ]]; then
-        echo "Invalid filename"
+        error "Invalid filename"
         return 1
     fi
 
     if [[ "$1" != *.md ]]; then
-        echo "Invalid extension"
+        error "Invalid extension"
         return 1
     fi
 
 
     if ! loadFile evalMe content "$1"; then
-        echo "Unable to load file"
+        error "Unable to load file"
         return 1
     fi
 
     if ! eval "$evalMe"; then
-        echo "Failure to eval the returned file data"
+        error "Failure to eval the returned file data"
         return 1
     fi
 
@@ -90,42 +90,42 @@ testCsi() {
     fi
 
     if [[ ${content[Category]} =~ [^-A-Z0-9] ]]; then
-        echo "Invalid characters in category: ${content[Category]}"
+        error "Invalid characters in category: ${content[Category]}"
         return 1
     fi
 
     if [[ ! -f "../categories/${content[Category],,}.md" ]]; then
-        echo "Category does not exist: ${content[Category]}"
+        error "Category does not exist: ${content[Category]}"
         return 1
     fi
 
     if [[ ${content[Source]} =~ [^-A-Z0-9] ]]; then
-        echo "Invalid characters in source: ${content[Source]}"
+        error "Invalid characters in source: ${content[Source]}"
         return 1
     fi
 
     if [[ ! -f "../sources/${content[Source],,}.md" ]]; then
-        echo "Source does not exist: ${content[Source]}"
+        error "Source does not exist: ${content[Source]}"
         return 1
     fi
 
     if [[ ! "${content[Format]}" =~ ^\`.*\`$ ]]; then
-        echo "Format is not markdown code: ${content[Format]}"
+        error "Format is not markdown code: ${content[Format]}"
         return 1
     fi
 
     if [[ ! "${content['8-Bit Hex']}" =~ ^\`[0-9a-z\ \{\}.]*\`$ ]]; then
-        echo "8-Bit Hex is not lowercase hex in markdown: ${content['8-Bit Hex']}"
+        error "8-Bit Hex is not lowercase hex in markdown: ${content['8-Bit Hex']}"
         return 1
     fi
 
     if [[ ! "${content['7-Bit Hex']}" =~ ^\`[0-9a-z\ \{\}.]*\`$ ]]; then
-        echo "7-Bit Hex is not lowercase hex in markdown: ${content['7-Bit Hex']}"
+        error "7-Bit Hex is not lowercase hex in markdown: ${content['7-Bit Hex']}"
         return 1
     fi
 
     if [[ ! "${content['Title']}" =~ ^\([A-Z]*\)(\ [A-Z][a-z]*)*$ ]]; then
-        echo "Poorly formatted title: ${content[Title]}"
+        error "Poorly formatted title: ${content[Title]}"
         return 1
     fi
 }
@@ -134,22 +134,22 @@ testSource() {
     local content evalMe
 
     if [[ "${1##*/}" =~ [^-a-z.0-9] ]]; then
-        errro "Invalid filename"
+        error "Invalid filename"
         return 1
     fi
 
     if [[ "$1" != *.md ]]; then
-        echo "Invalid extension"
+        error "Invalid extension"
         return 1
     fi
 
     if ! loadFile evalMe content "$1"; then
-        echo "Unable to load file" >&2
+        error "Unable to load file" >&2
         return 1
     fi
 
     if ! eval "$evalMe"; then
-        echo "Failure to eval the returned file data"
+        error "Failure to eval the returned file data"
         return 1
     fi
 
@@ -158,7 +158,7 @@ testSource() {
     fi
 
     if [[ "${content[Short]}" =~ [^-A-Z0-9] ]]; then
-        echo "Invalid characters in short code: ${content[Short]}"
+        error "Invalid characters in short code: ${content[Short]}"
         return 1
     fi
 }
@@ -169,36 +169,48 @@ cd "${0%/*}" || {
 }
 
 # shellcheck disable=SC1091
-. ./load-file
+. ./lib/load-file
+
+# shellcheck disable=SC1091
+. ./lib/status
 
 checked=0
 failures=0
 
 for file in ../categories/*; do
+    status "$file"
+
     if ! testCategory "$file"; then
-        echo "Problem with file: $file"
+        error "Problem with file: $file"
         failures=$((failures + 1))
     fi
 
     checked=$((checked + 1))
+    statusClear
 done
 
 for file in ../sources/*; do
+    status "$file"
+
     if ! testSource "$file"; then
-        echo "Problem with file: $file"
+        error "Problem with file: $file"
         failures=$((failures + 1))
     fi
 
     checked=$((checked + 1))
+    statusClear
 done
 
 for file in ../csi/*; do
+    status "$file"
+
     if ! testCsi "$file"; then
-        echo "Problem with file: $file"
+        error "Problem with file: $file"
         failures=$((failures + 1))
     fi
 
     checked=$((checked + 1))
+    statusClear
 done
 
 echo "$checked checked, $failures failures"
